// Mock data for app review without backend

export const mockUser = {
  id: '1',
  email: 'demo@fetchfiles.com',
  firstName: 'John',
  lastName: 'Doe',
  phone: '+1234567890',
  profileImage: null,
  isEmailVerified: true,
  twoFactorEnabled: false,
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const mockTokens = {
  accessToken: 'mock-access-token',
  refreshToken: 'mock-refresh-token',
  expiresIn: 900,
};

export const mockPets = [
  {
    id: '1',
    name: 'Bella',
    type: 'DOG',
    breed: 'Golden Retriever',
    gender: 'FEMALE',
    dateOfBirth: new Date('2020-05-15'),
    weight: 65,
    weightUnit: 'lbs',
    color: 'Golden',
    microchipId: 'MC12345678',
    profileImage: 'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=400',
    primaryOwnerId: '1',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Max',
    type: 'DOG',
    breed: 'Labrador',
    gender: 'MALE',
    dateOfBirth: new Date('2019-03-20'),
    weight: 75,
    weightUnit: 'lbs',
    color: 'Black',
    microchipId: 'MC87654321',
    profileImage: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400',
    primaryOwnerId: '1',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockVaccinations = [
  {
    id: '1',
    petId: '1',
    name: 'Rabies',
    administeredDate: new Date('2023-10-26'),
    expirationDate: new Date('2024-10-26'),
    nextDueDate: new Date('2024-10-26'),
    status: 'UP_TO_DATE',
    veterinarianName: 'Dr. Smith',
    clinicName: 'Pet Care Clinic',
  },
  {
    id: '2',
    petId: '1',
    name: 'DHPP',
    administeredDate: new Date('2023-10-26'),
    status: 'UP_TO_DATE',
    veterinarianName: 'Dr. Smith',
    clinicName: 'Pet Care Clinic',
  },
];

export const mockAppointments = [
  {
    id: '1',
    petId: '1',
    userId: '1',
    type: 'IN_PERSON_WELLNESS',
    status: 'SCHEDULED',
    scheduledDate: new Date('2024-01-15T14:00:00'),
    duration: 30,
    reason: 'Annual checkup',
    veterinarianName: 'Dr. Smith',
    clinicName: 'Pet Care Clinic',
    isVirtual: false,
  },
  {
    id: '2',
    petId: '2',
    userId: '1',
    type: 'VIRTUAL_CONSULTATION',
    status: 'SCHEDULED',
    scheduledDate: new Date('2024-01-20T10:00:00'),
    duration: 20,
    reason: 'Skin issue consultation',
    veterinarianName: 'Dr. Johnson',
    isVirtual: true,
  },
];

export const mockCareTasks = [
  {
    id: '1',
    petId: '1',
    type: 'MEDICATION',
    title: 'Give Morning Meds',
    assignedTo: '1',
    assignedBy: '1',
    scheduledTime: new Date('2024-01-01T08:00:00'),
    status: 'COMPLETED',
    priority: 'HIGH',
    dosage: '2 pills',
    medication: 'Amoxicillin',
    pet: mockPets[0],
  },
  {
    id: '2',
    petId: '1',
    type: 'EXERCISE',
    title: 'Evening Walk',
    assignedTo: '1',
    assignedBy: '1',
    scheduledTime: new Date('2024-01-01T18:00:00'),
    status: 'PENDING',
    priority: 'MEDIUM',
    pet: mockPets[0],
  },
  {
    id: '3',
    petId: '1',
    type: 'FEEDING',
    title: 'Full Bowl - Dry Food',
    assignedTo: '1',
    assignedBy: '1',
    scheduledTime: new Date('2024-01-01T17:00:00'),
    status: 'PENDING',
    priority: 'MEDIUM',
    pet: mockPets[0],
  },
  {
    id: '4',
    petId: '1',
    type: 'INSULIN_SHOT',
    title: 'Insulin Shot',
    assignedTo: '1',
    assignedBy: '1',
    scheduledTime: new Date('2024-01-01T07:00:00'),
    status: 'PENDING',
    priority: 'URGENT',
    dosage: '2 units',
    pet: mockPets[0],
  },
];

export const mockMedicalRecords = [
  {
    id: '1',
    petId: '1',
    type: 'VACCINATION',
    title: 'Rabies Vaccination',
    description: 'Annual rabies vaccination',
    date: new Date('2023-10-26'),
    veterinarianName: 'Dr. Smith',
    clinicName: 'Pet Care Clinic',
    attachments: [],
  },
  {
    id: '2',
    petId: '1',
    type: 'VISIT_SUMMARY',
    title: 'Annual Wellness Exam',
    description: 'Routine checkup - all vitals normal',
    date: new Date('2023-10-26'),
    veterinarianName: 'Dr. Smith',
    clinicName: 'Pet Care Clinic',
    attachments: [],
  },
];
